SPECIAL>NOINTERACTION
SPECIAL>LOADMODEL|EPS.mdl
SIMULATE>RUNNAME|CurrentRun
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[LDVs]=1.0
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[HDVs]=0.0
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[aircraft]=0.0
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[rail]=0.0
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[ships]=1.0
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[motorbikes]=0.9213910030476016
SIMULATE>SETVAL|Boolean EV Perks=1.0
SIMULATE>SETVAL|LDVs Feebate Rate=1.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[passenger,LDVs]=1.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[freight,LDVs]=1.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[passenger,HDVs]=0.7687982683062626
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[freight,HDVs]=1.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[passenger,motorbikes]=1.0
SIMULATE>SETVAL|Additional EV Subsidy Percentage[passenger,LDVs]=0.5
SIMULATE>SETVAL|Additional EV Subsidy Percentage[freight,HDVs]=0.5
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[gasoline vehicle,LDVs]=1.0
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[diesel vehicle,HDVs]=0.66
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[nonroad vehicle,aircraft]=0.0
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[nonroad vehicle,rail]=0.2
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[nonroad vehicle,ships]=0.2
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[gasoline vehicle,motorbikes]=0.0
SIMULATE>SETVAL|Fraction of TDM Package Implemented[passenger]=0.0
SIMULATE>SETVAL|Fraction of TDM Package Implemented[freight]=1.0
SIMULATE>SETVAL|Additional LCFS Percentage=0.0
SIMULATE>SETVAL|Percent New Nonelec Component Sales Shifted to Elec[urban residential]=1.0
SIMULATE>SETVAL|Percent New Nonelec Component Sales Shifted to Elec[rural residential]=1.0
SIMULATE>SETVAL|Percent New Nonelec Component Sales Shifted to Elec[commercial]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[heating,urban residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[cooling and ventilation,urban residential]=0.05034242466965523
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[envelope,urban residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[lighting,urban residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[appliances,urban residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[other component,urban residential]=0.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[heating,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[cooling and ventilation,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[envelope,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[lighting,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[appliances,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[other component,rural residential=0.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[heating,commercial]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[cooling and ventilation,commercial]=0.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[envelope,commercial]=0.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[lighting,commercial]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[appliances,commercial]=0.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[other component,commercial]=1.0
SIMULATE>SETVAL|Boolean Improved Contractor Edu and Training=1.0
SIMULATE>SETVAL|Min Fraction of Total Elec Demand to be Met by Distributed Solar PV=0.0
SIMULATE>SETVAL|Perc Subsidy for Distributed Solar PV Capacity=0.5
SIMULATE>SETVAL|Boolean Improved Device Labeling=1.0
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[heating]=0.034
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[cooling and ventilation]=0.0
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[envelope]=0.0
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[lighting]=0.034
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[appliances]=0.0
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[other component]=0.034
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[heating]=1.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[cooling and ventilation]=0.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[envelope]=1.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[lighting]=1.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[appliances]=1.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[hard coal es]=0.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[natural gas nonpeaker es]=0.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[nuclear es]=1.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[hydro es]=0.0
SIMULATE>SETVAL|Percent Change in Electricity Exports=-0.5
SIMULATE>SETVAL|Percent Change in Electricity Imports=1.0
SIMULATE>SETVAL|Annual Additional Capacity Retired due to Early Retirement Policy[hard coal es]=0.0
SIMULATE>SETVAL|Percentage Increase in Transmission Capacity vs BAU=1.0
SIMULATE>SETVAL|Boolean Use Non BAU Mandated Capacity Construction Schedule=0.0
SIMULATE>SETVAL|Nuclear Capacity Lifetime Extension=0.0
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[natural gas nonpeaker es,preexisting retiring]=0.0
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[onshore wind es,newly built]=0.25
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[solar pv es,newly built]=0.3
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[offshore wind es,newly built]=0.0
SIMULATE>SETVAL|Percent Reduction in Soft Costs of Capacity Construction[onshore wind es]=0.0
SIMULATE>SETVAL|Percent Reduction in Soft Costs of Capacity Construction[solar pv es]=0.9
SIMULATE>SETVAL|Percent Reduction in Soft Costs of Capacity Construction[offshore wind es]=0.0
SIMULATE>SETVAL|Percentage TnD Losses Avoided=0.6
SIMULATE>SETVAL|Additional Renewable Portfolio Std Percentage=0.8
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[onshore wind es]=60.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[solar pv es]=27.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[solar thermal es]=0.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[biomass es]=60.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[geothermal es]=0.0
SIMULATE>SETVAL|Fraction of Cement Clinker Substitution Made=0.0
SIMULATE>SETVAL|Fraction of Potential Cogeneration and Waste Heat Recovery Adopted=1.0
SIMULATE>SETVAL|Fraction of Energy Savings from Early Facility Retirement Achieved=1.0
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[cement and other carbonates]=0.0
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[natural gas and petroleum systems]=0.33
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[iron and steel]=0.0
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[chemicals]=0.0
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[mining]=0.33
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[waste management]=0.33
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[agriculture]=0.33
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[other industries]=0.32995050946580806
SIMULATE>SETVAL|Fraction of Installation and System Integration Issues Remedied=1.0
SIMULATE>SETVAL|Fraction of Hard Coal Use Converted to Other Fuels=0.0
SIMULATE>SETVAL|Fraction of Natural Gas Use Converted to Other Fuels=0.5
SIMULATE>SETVAL|Fraction of Methane Capture Opportunities Achieved=1.0
SIMULATE>SETVAL|Fraction of Methane Destruction Opportunities Achieved=0.0
SIMULATE>SETVAL|Fraction of F Gases Avoided=1.0
SIMULATE>SETVAL|Fraction of Addressable Process Emissions Avoided via Worker Training=1.0
SIMULATE>SETVAL|Fraction of Afforestation and Reforestation Achieved=1.0
SIMULATE>SETVAL|Fraction of Avoided Deforestation Achieved=1.0
SIMULATE>SETVAL|Fraction of Forest Set Asides Achieved=0.0
SIMULATE>SETVAL|Fraction of Abatement from Cropland Management Achieved=1.0
SIMULATE>SETVAL|Fraction of Improved Forest Management Achieved=1.0
SIMULATE>SETVAL|Fraction of Abatement from Livestock Measures Achieved=1.0
SIMULATE>SETVAL|Fraction of Potential Additional CCS Achieved=1.0
SIMULATE>SETVAL|Carbon Tax[transportation sector]=350.0
SIMULATE>SETVAL|Carbon Tax[electricity sector]=350.0
SIMULATE>SETVAL|Carbon Tax[residential buildings sector]=350.0
SIMULATE>SETVAL|Carbon Tax[commercial buildings sector]=350.0
SIMULATE>SETVAL|Carbon Tax[industry sector]=350.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[hard coal]=1.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[natural gas]=0.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[petroleum gasoline]=1.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[petroleum diesel]=1.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[jet fuel]=1.0
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[electricity]=0.0
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[hard coal]=0.0
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[natural gas]=0.4
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[petroleum gasoline]=0.4
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[petroleum diesel]=0.0
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[heating]=0.4
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[cooling and ventilation]=0.4
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[envelope]=0.4
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[lighting]=0.4
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[appliances]=0.4
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[other component]=0.0
SIMULATE>SETVAL|RnD CCS Capital Cost Perc Reduction=0.0
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[hard coal es]=0.0
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[natural gas nonpeaker es]=0.030257359541224087
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[nuclear es]=0.4
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[hydro es]=0.4
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[onshore wind es]=0.4
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[solar pv es]=0.0
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[solar thermal es]=0.0
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[biomass es]=0.4
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[natural gas peaker es]=0.4
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[offshore wind es]=0.0
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[cement and other carbonates]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[natural gas and petroleum systems]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[iron and steel]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[chemicals]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[mining]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[waste management]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[agriculture]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[other industries]=0.4
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[battery electric vehicle]=0.4
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[natural gas vehicle]=0.4
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[gasoline vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[diesel vehicle]=0.4
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[plugin hybrid vehicle]=0.4
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[nonroad vehicle]=0.4
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[heating]=0.0
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[cooling and ventilation]=0.0
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[lighting]=0.0
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[appliances]=0.4
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[other component]=0.4
SIMULATE>SETVAL|RnD CCS Fuel Use Perc Reduction=0.4
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[hard coal es]=0.0
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[natural gas nonpeaker es]=9.341008194809606E-4
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[nuclear es]=0.4
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[biomass es]=0.0
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[natural gas peaker es]=0.4
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[cement and other carbonates]=0.0
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[natural gas and petroleum systems]=0.4
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[iron and steel]=0.4
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[chemicals]=0.4
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[mining]=0.0
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[waste management]=0.0
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[agriculture]=0.0
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[other industries]=0.4
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[battery electric vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[natural gas vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[gasoline vehicle]=0.4
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[diesel vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[plugin hybrid vehicle]=0.3976072817985345
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[nonroad vehicle]=0.4
MENU>RUN|O
MENU>VDF2CSV|CurrentRun.vdf|RunResults.csv|OutputVarsToExport.lst
MENU>EXIT