SPECIAL>NOINTERACTION
SPECIAL>LOADMODEL|EPS.mdl
SIMULATE>RUNNAME|CurrentRunOdd
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[LDVs]=0.530868308
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[HDVs]=0.488345187
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[aircraft]=0.806000952
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[rail]=0.782984619
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[ships]=0.795069195
SIMULATE>SETVAL|Percentage Reduction of Separately Regulated Pollutants[motorbikes]=0.341447938
SIMULATE>SETVAL|Boolean EV Perks=0.0
SIMULATE>SETVAL|LDVs Feebate Rate=0.047292781
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[passenger,LDVs]=0.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[freight,LDVs]=0.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[passenger,HDVs]=0.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[freight,HDVs]=1.0
SIMULATE>SETVAL|Additional Minimum Required EV Sales Percentage[passenger,motorbikes]=0.100314134
SIMULATE>SETVAL|Additional EV Subsidy Percentage[passenger,LDVs]=0.319772641
SIMULATE>SETVAL|Additional EV Subsidy Percentage[freight,HDVs]=0.5
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[gasoline vehicle,LDVs]=0.341672533
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[diesel vehicle,HDVs]=0.447828855
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[nonroad vehicle,aircraft]=0.118215233
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[nonroad vehicle,rail]=0.177575793
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[nonroad vehicle,ships]=0.107732466
SIMULATE>SETVAL|Percentage Additional Improvement of Fuel Economy Std[gasoline vehicle,motorbikes]=0.087864549
SIMULATE>SETVAL|Fraction of TDM Package Implemented[passenger]=0.067262655
SIMULATE>SETVAL|Fraction of TDM Package Implemented[freight]=0.0
SIMULATE>SETVAL|Additional LCFS Percentage=0.4
SIMULATE>SETVAL|Percent New Nonelec Component Sales Shifted to Elec[urban residential]=0.563548543
SIMULATE>SETVAL|Percent New Nonelec Component Sales Shifted to Elec[rural residential]=0.958035761
SIMULATE>SETVAL|Percent New Nonelec Component Sales Shifted to Elec[commercial]=0.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[heating,urban residential]=0.73691864
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[cooling and ventilation,urban residential]=0.135879726
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[envelope,urban residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[lighting,urban residential]=0.724851589
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[appliances,urban residential]=0.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[other component,urban residential]=0.493362258
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[heating,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[cooling and ventilation,rural residential]=0.166734309
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[envelope,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[lighting,rural residential]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[appliances,rural residential]=0.238844984
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[other component,rural residential=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[heating,commercial]=0.313767381
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[cooling and ventilation,commercial]=0.571568533
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[envelope,commercial]=0.866275076
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[lighting,commercial]=1.0
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[appliances,commercial]=0.311779385
SIMULATE>SETVAL|Reduction in E Use Allowed by Component Eff Std[other component,commercial]=0.725216758
SIMULATE>SETVAL|Boolean Improved Contractor Edu and Training=1.0
SIMULATE>SETVAL|Min Fraction of Total Elec Demand to be Met by Distributed Solar PV=0.0
SIMULATE>SETVAL|Perc Subsidy for Distributed Solar PV Capacity=0.5
SIMULATE>SETVAL|Boolean Improved Device Labeling=1.0
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[heating]=0.020892572
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[cooling and ventilation]=0.016343342
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[envelope]=0.008427541
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[lighting]=0.030049879
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[appliances]=0.011361794
SIMULATE>SETVAL|Fraction of Commercial Components Replaced Annually due to Retrofitting Policy[other component]=0.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[heating]=0.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[cooling and ventilation]=0.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[envelope]=1.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[lighting]=0.0
SIMULATE>SETVAL|Boolean Rebate Program for Efficient Components[appliances]=0.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[hard coal es]=1.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[natural gas nonpeaker es]=0.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[nuclear es]=0.0
SIMULATE>SETVAL|Boolean Ban New Power Plants[hydro es]=0.0
SIMULATE>SETVAL|Percent Change in Electricity Exports=1.0
SIMULATE>SETVAL|Percent Change in Electricity Imports=0.910292492
SIMULATE>SETVAL|Annual Additional Capacity Retired due to Early Retirement Policy[hard coal es]=993.0
SIMULATE>SETVAL|Percentage Increase in Transmission Capacity vs BAU=0.137066252
SIMULATE>SETVAL|Boolean Use Non BAU Mandated Capacity Construction Schedule=1.0
SIMULATE>SETVAL|Nuclear Capacity Lifetime Extension=18.0
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[natural gas nonpeaker es,preexisting retiring]=0.381956898
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[onshore wind es,newly built]=0.107377619
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[solar pv es,newly built]=0.0
SIMULATE>SETVAL|Percentage Reduction in Plant Downtime[offshore wind es,newly built]=0.25
SIMULATE>SETVAL|Percent Reduction in Soft Costs of Capacity Construction[onshore wind es]=0.9
SIMULATE>SETVAL|Percent Reduction in Soft Costs of Capacity Construction[solar pv es]=0.0
SIMULATE>SETVAL|Percent Reduction in Soft Costs of Capacity Construction[offshore wind es]=0.312214231
SIMULATE>SETVAL|Percentage TnD Losses Avoided=0.279927225
SIMULATE>SETVAL|Additional Renewable Portfolio Std Percentage=0.212294442
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[onshore wind es]=46.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[solar pv es]=48.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[solar thermal es]=0.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[biomass es]=36.0
SIMULATE>SETVAL|Subsidy for Elec Production by Fuel[geothermal es]=2.0
SIMULATE>SETVAL|Fraction of Cement Clinker Substitution Made=0.0
SIMULATE>SETVAL|Fraction of Potential Cogeneration and Waste Heat Recovery Adopted=1.0
SIMULATE>SETVAL|Fraction of Energy Savings from Early Facility Retirement Achieved=0.0
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[cement and other carbonates]=0.14837461
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[natural gas and petroleum systems]=0.099462251
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[iron and steel]=0.33
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[chemicals]=0.154361282
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[mining]=0.038547159
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[waste management]=0.0
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[agriculture]=0.253298613
SIMULATE>SETVAL|Percentage Improvement in Eqpt Efficiency Standards above BAU[other industries]=0.311747029
SIMULATE>SETVAL|Fraction of Installation and System Integration Issues Remedied=0.439110885
SIMULATE>SETVAL|Fraction of Hard Coal Use Converted to Other Fuels=0.497690269
SIMULATE>SETVAL|Fraction of Natural Gas Use Converted to Other Fuels=0.0
SIMULATE>SETVAL|Fraction of Methane Capture Opportunities Achieved=0.415619312
SIMULATE>SETVAL|Fraction of Methane Destruction Opportunities Achieved=0.185308425
SIMULATE>SETVAL|Fraction of F Gases Avoided=0.454092928
SIMULATE>SETVAL|Fraction of Addressable Process Emissions Avoided via Worker Training=0.98605796
SIMULATE>SETVAL|Fraction of Afforestation and Reforestation Achieved=0.373643081
SIMULATE>SETVAL|Fraction of Avoided Deforestation Achieved=0.630100441
SIMULATE>SETVAL|Fraction of Forest Set Asides Achieved=0.98871777
SIMULATE>SETVAL|Fraction of Abatement from Cropland Management Achieved=0.345305185
SIMULATE>SETVAL|Fraction of Improved Forest Management Achieved=0.0
SIMULATE>SETVAL|Fraction of Abatement from Livestock Measures Achieved=0.54984443
SIMULATE>SETVAL|Fraction of Potential Additional CCS Achieved=0.948176932
SIMULATE>SETVAL|Carbon Tax[transportation sector]=302.0
SIMULATE>SETVAL|Carbon Tax[electricity sector]=151.0
SIMULATE>SETVAL|Carbon Tax[residential buildings sector]=350.0
SIMULATE>SETVAL|Carbon Tax[commercial buildings sector]=350.0
SIMULATE>SETVAL|Carbon Tax[industry sector]=350.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[hard coal]=0.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[natural gas]=0.0
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[petroleum gasoline]=0.954836188
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[petroleum diesel]=0.470360099
SIMULATE>SETVAL|Percent Reduction in BAU Subsidies[jet fuel]=1.0
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[electricity]=0.135135551
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[hard coal]=0.163601352
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[natural gas]=0.043531748
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[petroleum gasoline]=0.294405293
SIMULATE>SETVAL|Additional Fuel Tax Rate by Fuel[petroleum diesel]=0.067508561
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[heating]=0.30722168
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[cooling and ventilation]=0.0
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[envelope]=0.4
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[lighting]=0.361607257
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[appliances]=0.0
SIMULATE>SETVAL|RnD Building Capital Cost Perc Reduction[other component]=0.055575278
SIMULATE>SETVAL|RnD CCS Capital Cost Perc Reduction=0.0
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[hard coal es]=0.057892995
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[natural gas nonpeaker es]=0.235007922
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[nuclear es]=0.244896102
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[hydro es]=0.4
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[onshore wind es]=0.385044492
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[solar pv es]=0.302326031
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[solar thermal es]=0.030283165
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[biomass es]=0.4
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[natural gas peaker es]=0.284347245
SIMULATE>SETVAL|RnD Electricity Capital Cost Perc Reduction[offshore wind es]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[cement and other carbonates]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[natural gas and petroleum systems]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[iron and steel]=0.080104222
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[chemicals]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[mining]=0.296380908
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[waste management]=0.00277196
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[agriculture]=0.4
SIMULATE>SETVAL|RnD Industry Capital Cost Perc Reduction[other industries]=0.361020717
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[battery electric vehicle]=0.096283502
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[natural gas vehicle]=0.22586074
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[gasoline vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[diesel vehicle]=0.4
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[plugin hybrid vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Capital Cost Perc Reduction[nonroad vehicle]=0.052900552
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[heating]=0.0
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[cooling and ventilation]=0.318884119
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[lighting]=0.0
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[appliances]=0.312830366
SIMULATE>SETVAL|RnD Building Fuel Use Perc Reduction[other component]=0.254664164
SIMULATE>SETVAL|RnD CCS Fuel Use Perc Reduction=0.073439388
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[hard coal es]=0.072228495
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[natural gas nonpeaker es]=0.4
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[nuclear es]=0.4
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[biomass es]=0.293016148
SIMULATE>SETVAL|RnD Electricity Fuel Use Perc Reduction[natural gas peaker es]=0.4
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[cement and other carbonates]=0.4
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[natural gas and petroleum systems]=0.4
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[iron and steel]=0.210526634
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[chemicals]=0.044323402
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[mining]=0.191238241
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[waste management]=0.00858257
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[agriculture]=0.346122966
SIMULATE>SETVAL|RnD Industry Fuel Use Perc Reduction[other industries]=0.0
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[battery electric vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[natural gas vehicle]=0.306843071
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[gasoline vehicle]=0.161009052
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[diesel vehicle]=0.0
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[plugin hybrid vehicle]=0.4
SIMULATE>SETVAL|RnD Transportation Fuel Use Perc Reduction[nonroad vehicle]=0.020939709
MENU>RUN|O
MENU>VDF2CSV|CurrentRunOdd.vdf|RunResultsOdd.csv|OutputVarsToExport.lst
MENU>EXIT